export const ROUTES = {
  MOVIESSCREEN: 'MOVIESSCREEN',
  FAVOURITESSCREEN: 'FAVOURITESSCREEN',
  MOVIEDETAILSSCREEN: 'MOVIEDETAILSSCREEN',
  MOVIESTACKSCREEN: 'MOVIESTACKSCREEN',
  FAVOURITESTACKSCREEN: 'FAVOURITESTACKSCREEN',
  HOMESCREEN: 'HOMESCREEN',
  PROFILESCREEN: 'PROFILESCREEN',
  SEARCHSCREEN: 'SERCHSCREEN',
} as const;
