export const ROUTES = {
  MOVIESSCREEN: 'MoviesScreen',
  FAVOURITESSCREEN: 'FavouritesScreen',
  MOVIEDETAILSSCREEN: 'MovieDetailsScreen',
  MOVIESTACKSCREEN: 'MOVIESTACKSCREEN',
  FAVOURITESTACKSCREEN: 'FAVOURITESTACKSCREEN',
  HOMESCREEN: 'HOMESCREEN',
  PROFILESCREEN: 'PROFILESCREEN',
} as const;
type RouteKeys = keyof typeof ROUTES;
